### PR TITLE
AddServiceBuildingType: skip asking on lifecycle prefixes too

### LINKED ISSUE #767: Don't ask for type of service building if disused service is tagged on it
**How to Reproduce**
Have a building=service with disused:power=substation on it (like https://www.openstreetmap.org/way/1327381560), it will show up as a quest asking what sort of service building it is.

**Expected Behavior**
It shouldn't ask what sort of service building something is if it is marked as a disused service (or at least not for a suitable resurvey time period). It may also be useful to have a way of selecting that it is a disused service building in the quest too, maybe?

**Does it happen in normal StreetComplete?**
I don't think this quest is in normal SC.

**Versions affected**
I'm using v60.3 on Android 15

### PR DESCRIPTION
**Pull request by mnalis**
(i.e. `disused` / `abandoned` / `was` / `construction`)

It also adds `It's disused` otherAnswer to both service building quests.

Fixes https://github.com/Helium314/SCEE/issues/767

I've done some basic testing, but more testing (esp. of `It's disused` otherAnswer) would be appreciated. debug `.apk` is available [here](https://github.com/mnalis/StreetComplete/actions/runs/14586398152). @dbdean would you like to try it?

### CODE REVIEW

**Comment by dbdean** [comment]
The built apk seems to be working. It doesn't show my unused service building at https://www.openstreetmap.org/way/1327381560, and marking https://www.openstreetmap.org/way/1329023879/history as disused seemed to work (which I then undoed).

File: app/src/main/java/de/westnordost/streetcomplete/quests/service_building/AddServiceBuildingType.kt [hunk 1]
```diff
@@ -10,13 +10,14 @@ class AddServiceBuildingType : OsmFilterQuestType<ServiceBuildingType>() {
...
-          and !utility
-          and !railway
+          and !power and !disused:power and !abandoned:power and !was:power and !construction:power
+          and !service and !disused:service and !abandoned:service and !was:service and !construction:service
+          and !man_made and !disused:man_made and !abandoned:man_made and !was:man_made and !construction:man_made
+          and !substation and !disused:substation and !abandoned:substation and !was:substation and !construction:substation
+          and !pipeline and !disused:pipeline and !abandoned:pipeline and !was:pipeline and !construction:pipeline
+          and !utility and !disused:utility and !abandoned:utility and !was:utility and !construction:utility
+          and !railway and !disused:railway and !abandoned:railway and !was:railway and !construction:railway
+          and disused != yes and abandoned != yes and !construction
```
Comment (dbdean) [inline app/src/main/java/de/westnordost/streetcomplete/quests/service_building/AddServiceBuildingType.kt:20]: would it make sense to build this programmatically? I think SC does something similar with place types at https://github.com/streetcomplete/StreetComplete/blob/71bbf8e73cb9db2406d4c9f143abf08e773ea2ca/app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt#L12-L15C1

**Comment by Helium314** [comment]
Should be fine, though I'm not sure whether just `disused=yes` is ok. From the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:disused%3Dyes) it seems any power / utility / ... tag should get a `disused:` prefix?

File: app/src/main/java/de/westnordost/streetcomplete/quests/service_building/AddServiceBuildingType.kt (hunk 1 above)
Comment (Helium314) [reply app/src/main/java/de/westnordost/streetcomplete/quests/service_building/AddServiceBuildingType.kt:20]: I agree it's easier to build, but now it's already done and still readable enough.

Comment (mnalis) [reply app/src/main/java/de/westnordost/streetcomplete/quests/service_building/AddServiceBuildingType.kt:20]: Yeah I considered it, but then I was worried that the quest selectionElement wouldn't be normally editable by users, so I decided on copy/paste.

**Comment by mnalis** [comment]
> Should be fine, though I'm not sure whether just `disused=yes` is ok. From the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:disused%3Dyes) it seems any power / utility / ... tag should get a `disused:` prefix?

Good point!

I based `disused=yes` on _"What kind of service building is this"_ quest (which will **never** even be asked if `power` / `utility` / etc. tags exist)... So `disused=yes` is good there to remove it from being asked (as we can't make it `disused:power=*` or similar, because we don't know it if was `power=*` or something else)

But for _"Who is the operator for this service building?"_, it might indeed be already tagged with e.g. `power=substation`, and we should definitely replace that (and all similar) with `disused:power=substation` instead of just adding `disused=yes`.

**Comment by mnalis** [comment]
Ok, now, when marked as disused in service building operator quest, it should also be prefixing any existing e.g. `utility` / `power` / `service` / etc. tags with `disused:` prefix.

debug .apk is [here](https://github.com/mnalis/StreetComplete/actions/runs/14609013163)
